export const HOMEPAGE = '/'
export const SINGLE_LIST = '/product/:id'
export const ADMIN_PANEL = '/admin'
export const ADMIN_PRODUCTS = '/admin/products'
export const LOGIN = '/login'
export const SIGN_UP = '/sign_up'
